runtime: nodejs18

env_variables:
  NODE_ENV: 'development'
  USER_PORT: 8080
  JWTKEY: 'asldjfldsjlfsf'
  TOKEN_EXPIRATION: 'hour || minutes || 48h'
  DB_HOST_DEV: /cloudsql/rapid-bricolage-444914-c5:asia-south1:ib3d
  DB_PORT_DEV: 5432
  DB_USER_DEV: 'ib3d'
  DB_PASSWORD_DEV: 'ib3d@2025AppDev'
  DB_NAME_DEV: 'ib3d'
  DB_DIALECT_DEV: 'postgres'
  ASSETS_PATH_DEV: 'http://localhost:3000'
manual_scaling:
  instances: 1
